### ISSUE TITLE
A small typo in the readme

### ISSUE THREAD

**Issue by morsingher** [TRI-ML/camviz#3]
Hi, thanks for finally open sourcing this! Just a quick suggestion: fix the typo in the installation part. The correct command should be:
```
git clone git@github.com:TRI-ML/camviz.git
```
instead of:
```
git clone git@github.com:TRI-ML/camviz_internal.git
```
It also works on Ubuntu 20.04, just for the record. Have a nice day :)

**Comment by VitorGuizilini-TRI** [comment]
Thank you, I have updated the README!
